"use strict";
let currentTab, navigationResult, sharingResult, originalUrl;
function log(event, details={}) { console.info(`[Uncruft] ${event}`,details); try{ext.runtime.sendMessage({type:"popup-log",event,details});}catch(_){} }
function showStatus(message,isError=false){const e=document.querySelector("#status");e.textContent=message;e.className=isError?"status error":"status ok";}
async function queryActiveTab(){const r=ext.tabs.query({active:true,currentWindow:true});if(r&&typeof r.then==="function")return r;return new Promise((resolve,reject)=>ext.tabs.query({active:true,currentWindow:true},tabs=>{const e=ext.runtime.lastError;e?reject(new Error(e.message)):resolve(tabs);}));}
async function updateTab(tabId,url){const r=ext.tabs.update(tabId,{url});if(r&&typeof r.then==="function")return r;return new Promise((resolve,reject)=>ext.tabs.update(tabId,{url},tab=>{const e=ext.runtime.lastError;e?reject(new Error(e.message)):resolve(tab);}));}
async function sendMessage(message){try{const r=ext.runtime.sendMessage(message);if(r&&typeof r.then==="function")return r;}catch(_){}return new Promise((resolve,reject)=>ext.runtime.sendMessage(message,response=>{const e=ext.runtime.lastError;e?reject(new Error(e.message)):resolve(response);}));}
async function copyText(text){if(!text)throw new Error("There is no URL to copy.");try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return;}}catch(error){log("Clipboard API failed; trying fallback",{error:error.message});}const t=document.createElement("textarea");t.value=text;t.setAttribute("readonly","");t.style.position="fixed";t.style.opacity="0";document.body.appendChild(t);t.focus();t.select();const ok=document.execCommand("copy");t.remove();if(!ok)throw new Error("The browser rejected the clipboard operation.");}
function describeRemoved(result){if(!result.removed.length)return "No marketing or tracking parameters were found.";const host=new URL(result.original).hostname;return `Removed ${result.removed.length} marketing or tracking parameter${result.removed.length===1?"":"s"} from ${host}.`;}
async function loadActivity(){const response=await sendMessage({type:"get-activity"});const list=document.querySelector("#activity");const items=response?.activity??[];list.textContent="";if(!items.length){const li=document.createElement("li");li.textContent="No activity recorded yet.";list.appendChild(li);return;}for(const item of items.slice(0,5)){const li=document.createElement("li");const text=document.createElement("div");text.textContent=item.message;const time=document.createElement("time");time.textContent=new Date(item.timestamp).toLocaleString();li.append(text,time);list.appendChild(li);}}
(async()=>{try{[currentTab]=await queryActiveTab();if(!currentTab?.url)throw new Error("No readable URL is available for this tab.");const [{config},stateResponse]=await Promise.all([storageGet(["config"]),sendMessage({type:"get-navigation-state",tabId:currentTab.id}).catch(()=>null)]);const state=stateResponse?.state;originalUrl=state?.cleaned===currentTab.url?state.original:currentTab.url;navigationResult=cleanUrl(originalUrl,config);sharingResult=cleanUrlForSharing(originalUrl,config);document.querySelector("#url").textContent=sharingResult.cleaned;document.querySelector("#removed").textContent=sharingResult.removed.length?`Technical details: ${sharingResult.removed.join(", ")}`:"Nothing removed.";document.querySelector("#summary").textContent=describeRemoved(sharingResult);document.querySelector("#navigate").disabled=navigationResult.cleaned===currentTab.url;await loadActivity();log("Popup initialized",{tabId:currentTab.id,current:currentTab.url,original:originalUrl,clean:sharingResult.cleaned,removed:sharingResult.removed});}catch(error){document.querySelector("#summary").textContent=error.message;showStatus(error.message,true);log("Popup initialization failed",{error:error.message});}})();
document.querySelector("#navigate").addEventListener("click",async()=>{try{if(!currentTab||!navigationResult)throw new Error("No clean URL is available.");await updateTab(currentTab.id,navigationResult.cleaned);log("Navigate clean",{from:currentTab.url,to:navigationResult.cleaned});window.close();}catch(error){showStatus(error.message,true);}});
document.querySelector("#copy").addEventListener("click",async()=>{try{await copyText(sharingResult?.cleaned);showStatus("Clean link copied.");log("Copied clean link",{url:sharingResult.cleaned,removed:sharingResult.removed});}catch(error){showStatus(error.message,true);}});
document.querySelector("#copyOriginal").addEventListener("click",async()=>{try{await copyText(originalUrl);showStatus("Original link copied.");log("Copied original URL",{url:originalUrl});}catch(error){showStatus(error.message,true);}});
document.querySelector("#options").addEventListener("click",()=>ext.runtime.openOptionsPage());
document.querySelector("#clearActivity").addEventListener("click",async()=>{await sendMessage({type:"clear-activity"});await loadActivity();showStatus("Activity cleared.");});
document.querySelector("#runTests").addEventListener("click",()=>{ext.tabs.create({url:ext.runtime.getURL("test-runner.html")});window.close();});
